#!/bin/bash
# given a TMS dir generated by gdal2tiles.py, rename the row index to
# make it conform to google tile indexing standard:
# tile (0,0): google is upper left; tms is lower left
[ ! -d "$1" ] && echo "ERROR: $1 is not a dir." && exit 1
d="$1" # input dir
d2="$2" # output dir
[ ! -d "$d2" ] && mkdir -p $d2
suffix=png
echo "$d -> $d2"
[ -f $d/extent.txt ] && cp $d/extent.txt $d2/
for zd in `ls -d $d/*/`
do
    z=`echo "$zd" | awk -F\/ '{print \$(NF-1)}'`
    numrows=`echo "2^$z" | bc`
    for col in `ls $zd`
    do
        for img in `ls $zd/$col/*.$suffix`
        do
            row=`basename $img .$suffix`
            let "newrow=$numrows - $row - 1"
            #echo -e "$z\t($col,$row) -> ($col,$newrow)"
            odir=$d2/$z/$col
            [ ! -d $odir ] && mkdir -p $odir
            cp $img $odir/$newrow.$suffix
        done
    done
done
